#!/bin/bash

npm install express multer csv-parser express-session

osascript <<EOF
tell application "Terminal"
    do script "cd $(pwd) && node server.js"
end tell
EOF

sleep 3

open -a Safari http://localhost:3000